### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by RuthSalvador** [HillaryChumacero/lim-2018-05-bc-core-am-cipher#1]
# Recomendaciones de mejora 👍

- **`README.md`**: buena idea completar las 3 respuestas para la definición del producto. Puedes añadir como te organizaste durante estos 2 sprints, imágenes de la evolución de tu producto, las tecnologías que utilizaste.

- **`index.html`**: recuerda que debes validar tu `html`, te recomendamos revisar el enlace https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fhillarychumacero.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F para mayor especificación. Te sugerimos utilizar más etiquetas semánticas como `main`, `section`, etc; evita usar etiquetas como `<br>` para darle estilos o espacios, para ello se usa `css`.
No te olvides que las etiquetas `input`, `br` se autocierran con un `/>`. En cuanto al nombre de tus `id` y `class` evita que sean muy largas; debes mantener un estilo estándar, puedes usar solo la sintaxis con guion normal en lugar de subguión o camelCase (éste se usa más para las variables en `javascript`). Ej:
  ``` js
  const textInput = document.getElementById('text-input');
  ```
  Lo último que debe ir en el `body` son los `scripts`, no el `footer`. Evita utilizar la etiqueta `style` para agregar estilos, en su lugar usa `css`. Cuida tu indentación.

- **`cipher.js`**: buena lógica para las operaciones de cifrado y descifrado. Ten cuidado con tu indentación. Te recomendamos utilizar `for of` para utilizar la nueva sintaxis de `ES6`. Define mejor tus variables, evita colocar `x`, `texto` ya que no son descriptivas. Puedes refactorizar tu código utilizando una sola variable final e ir almacenando directamente ahí, en lugar de almacenarlo en `x` y luego unirlo. 

- **`index.js`**: buena idea declarar al inicio los elementos del DOM que utilizas. Recuerda declarar tus variables con nombres en inglés y descriptivas. Evita usar `/********************/` para separar eventos, con darle un enter es suficiente. Te sugerimos averiguar sobre `.classList.add` para que lo puedas usar en lugar de `style.display = 'none'`

- **`style.css`**: muy bien importando las fuentes. Ten cuidado al utilizar `flex`, `position`, `top`, etc; es mejor retirar los estilos que no usas. Recuerda utilizar clases descriptivas y la convención de usar inglés; te recomendamos crear clases para reutilizar estilos, cuida tu indentación que es importante.

- **Tests**: bien apuntar a una cobertura de 100%, recuerda que si deseas puedes agregar más tests para practicar.

Por último te recomendamos tener en cuenta la guía de estilos y utilizar comillas simples (' ') en archivos js y comillas dobles (" ") en el html. Además los usuarios pueden ver tu producto desde cualquier dispositivo, te recomendamos realizar tus proyectos responsive.

Sigue así buen trabajo 👍

**Comment by HillaryChumacero** [comment]
Muchas gracias, Ruth.  Aplicaré las indicaciones en el presente proyecto Data Dasboard.
Tengo una consulta, respecto a la indentación, ¿podría hacer  Alt+Shift+F  con espacio 2?
